name: .NET Full Build

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-build
