name: Build

on: [push, pull_request]

jobs:
  build-quick:
    name: Quick Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ./test/FlexLabs.EntityFrameworkCore.Upsert.Tests --no-build --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (quick)
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

  build-ubuntu:
    name: Full Build (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (ubuntu)
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx


  build-windows:
    name: Full Build (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'
    - uses: actions/checkout@v3
    - name: Enable Postgres
      run: sc config postgresql-x64-14 start= demand
    - name: Start Postgres
      run: net start postgresql-x64-14
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:POSTGRES_ONLY=true
    - name: Test
      env:
        USE_LOCAL_SERVICE: 'true'
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test Results (windows)
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

